### ISSUE TITLE
styles_picker.xml 

### ISSUE THREAD

**Issue by FrankLynCode** [cutler/AndroidTemplate#2]
fork了您的项目，clone后用android studio打开发现tp_base/src/main/res/values/styles_picker.xml 中缺失@drawable/tp_ic_picker_divider图片？

**Comment by FrankLynCode** [comment]
还是说datapickerdialog已经被博主舍弃了？

**Comment by cutler** [comment]
是我的失误，传项目的时候少传了一些文件，现在已经搞好了。
